### PR TITLE
fix: undeclared indirect dependencies

### PR DESCRIPTION
**Pull request by oliversalzburg**
Ensures that all modules that are consumed are also listed as dependencies in the manifest.

See: https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-doctor#no-unlisted-dependencies

Neglecting to declare these dependencies can (and already does) lead to them being unavailable in some module resolution mechanisms.

This issue manifests in errors such as:
```
../.yarn/cache/@material-mwc-select-npm-0.17.2-d80ce2ad81-36d9783eac.zip/node_modules/@material/mwc-select/mwc-select-base.d.ts:22:28 - error TS2307: Cannot find module '@material/list/typeahead.js' or its corresponding type declarations.
22 import * as typeahead from '@material/list/typeahead.js';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../.yarn/cache/@material-mwc-select-npm-0.17.2-d80ce2ad81-36d9783eac.zip/node_modules/@material/mwc-select/mwc-select-base.d.ts:23:37 - error TS2307: Cannot find module '@material/list/types' or its corresponding type declarations.
23 import { MDCListTextAndIndex } from '@material/list/types';
```

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Seems like the build was broken by 3d334ccc90119a49df7510910d423ca9edb76a64 I can rebase later if needed

**Comment by e111077** [comment]
Heya, thanks for the work on this! Do you mind fixing the conflicting files and tagging them to the same versions? e.g. mwc elements to `^0.17.2` lit-element and lit-html to the same as what is set on other files, as well as all MDC files to the latest canary?
